baseURL: https://www.prototim.com/
languageCode: en-gb
title: Tim Jones - Prototype Geek
theme: toha

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - JSON

enableEmoji: true

params:
  enableBlogPost: true
  enableTOC: false
  newsletter:
    enable: false

  background: /images/site/background.jpg
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/main-logo.png
    favicon: /images/site/main-logo.png

  gitRepo: https://github.com/TimJones/prototim-site
