[build]
  publish = "public/"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.93.3"

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
