name: Hugo build
on:
  pull_request:

jobs:
  build:
    name: Hugo build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.0'
    - name: build
      run: hugo --gc --minify
