name: Check Hugo Version
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  update-hugo:
    name: Update Hugo to latest release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: update-hugo-ver-env
      id: depup
      uses: reviewdog/action-depup@v1
      with:
        file: .env
        version_name: HUGO_VERSION
        repo: gohugoio/hugo
    - name: update-hugo-ver-netlify
      uses: reviewdog/action-depup@v1
      with:
        file: netlify.toml
        version_name: HUGO_VERSION
        repo: gohugoio/hugo
    - name: create-pr
      uses: peter-evans/create-pull-request@v4
      with:
        branch: hugo-update-${{ steps.depup.outputs.latest }}
        title: "chore (deps): Update Hugo version to ${{ steps.depup.outputs.latest }}"
        commit-message: "chore (deps): Update Hugo version to ${{ steps.depup.outputs.latest }}"
        body: |
          Update Hugo to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})
          This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
